# https://stackoverflow.com/questions/185936/how-to-delete-the-contents-of-a-folder
import os
import shutil

# NOTE: a cleanup file derived from this file on the Pi uses 
# an efficient approach for removing dirs with subdirs. 

def partial_cleanup():
    """
    Does not remove `Files/poi.csv`, this file is generated by the GUI and is therefore
    run once per batch/ cycle. However the data from the previous board in the batch needs
    to be removed, this function does that. 
    """
    try:
        os.remove("Files/roi.csv")
        os.remove("Files/rects.csv")
        shutil.rmtree("Assets/")
        shutil.rmtree("COM/")
        shutil.rmtree("POI/")
    except Exception as e:
        print(e) 
    
    # Directories with the following names are made (useful for first run)
    os.makedirs(os.getcwd()+"/Assets/", exist_ok=True)
    os.makedirs(os.getcwd()+"/COM/", exist_ok=True)
    os.makedirs(os.getcwd()+"/POI/", exist_ok=True)
    os.makedirs(os.getcwd()+"/POI/BOARD/", exist_ok=True)


def cleanup():
    """
    Used to remove all data collected and created from the previous run. 
    Each image under test needs a clean an environment to avoid data contamination

    ## Run this file to start afresh

    @output: **empty** Files, Assets, COM, POI directories
    """ 
    try:
        shutil.rmtree("Files/") 
        shutil.rmtree("Assets/")
        shutil.rmtree("COM/")
        shutil.rmtree("POI/")
    except Exception as e:
        print(e) 
    
    # Directories with the following names are made (useful for first run)
    os.makedirs(os.getcwd()+"/Files/", exist_ok=True)
    os.makedirs(os.getcwd()+"/Assets/", exist_ok=True)
    os.makedirs(os.getcwd()+"/COM/", exist_ok=True)
    os.makedirs(os.getcwd()+"/POI/", exist_ok=True)
    os.makedirs(os.getcwd()+"/POI/BOARD/", exist_ok=True)
     

if __name__ == "__main__":
    cleanup()